#!/usr/bin/python

USERNAME ='waheedsultan2003@yahoo.com'
PASSWORD ='coeus123'
BASE_DOWNLOAD_PATH = '/home/abdullah/Tuts/'
SUBS = True
COURSES = [
	'google-calendar-essential-training-2',
	'xml-essential-training-2',
	'quickbooks-payroll-essential-training',
	'advanced-google-analytics-2',
	'maya-2018-essential-training',
	'google-sites-essential-training-2',
	'learning-apache-cordova',
	'wordpress-5-essential-training',
	'building-solutions-using-excel-and-access-2019-together',
	'programming-foundations-object-oriented-design-3',
	'excel-in-the-real-world',
	'leading-with-emotional-intelligence-3',
	'macos-mojave-essential-training',
	'macos-mojave-new-features',
	'windows-10-networking-2',
	'troubleshooting-common-pc-issues-for-users-2',
	'communicating-across-cultures-2',
	'seo-foundations-2',
	'after-effects-cc-2019-essential-training-the-basics',
	'excel-introduction-to-formulas-and-functions',
	'bootstrap-4-layouts-responsive-single-page-design',
	'enhancing-resilience',
	'learning-linux-command-line-2',
	'customer-service-foundations-2',
	'online-marketing-foundations-3',
	'windows-10-for-it-pros-essential-training',
	'photoshop-cc-2019-essential-training-the-basics',
	'photoshop-cc-2019-essential-training-design',
	'photoshop-cc-2019-essential-training-photography',
	'targeted-adjustments-in-photoshop-cc',
	'mastering-selections-in-photoshop-cc-2',
	'photoshop-cc-2018-one-on-one-mastery',
	'photoshop-cc-2018-one-on-one-advanced',
	'photoshop-cc-2018-one-on-one-fundamentals',
	'photoshop-tips-tricks-techniques-2',
	'photoshop-selections-tips-tricks-and-techniques',
	'magento-module-creation-and-customization-techniques',
	'plangrid-managing-construction-activities',
	'job-interview-strategies-for-ux-designers',
	'developing-investment-acumen',
	'azure-event-grid',
	'microsoft-certifications-exams-paths-certifications-and-resources-2',
	'bigcommerce-essential-training',
	'windows-server-2019-active-directory-enterprise-infrastructure',
	'python-data-structures-stacks-queues-and-deques',
	'rhce-cert-prep-network-filesystems-using-nfs-and-samba',
	'linux-foundation-cert-prep-network-filesystems-and-file-services-ubuntu'
]

WEEKLY = [
	'excel-weekly-challenge',
	'agile-challenges-weekly-tips',
	'help-yourself-tech-tips-weekly',
	'agile-analysis-weekly-tips',
	'microsoft-project-tips-weekly',
	'linux-tips-weekly',
	'supply-chain-and-operations-management-weekly-tips',
	'personal-finance-tips-weekly-2',
	'career-clinic-developer-insights',
	'consulting-professional-weekly-tips',
	'security-tips-weekly',
	'administrative-professional-weekly-tips',
	'leadership-stories-weekly',
	'word-tips-weekly',
	'product-management-weekly-tips',
	'monday-productivity-pointers',
	'css-shorts-weekly',
	'finance-and-accounting-tips-weekly',
	'management-tips-weekly',
	'training-tips-weekly',
	'web-career-clinic-weekly',
	'happiness-tips-weekly',
	'marketing-tips-weekly',
	'communication-tips-weekly',
	'powerpoint-tips-weekly',
	'time-management-tips-weekly',
	'excel-tips-weekly'
]